// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJpSeC-vv56xjAbiGVhUOj6JkMieEfb7Y',
    appId: '1:272005928943:web:d00c6f1a888252a8b1c81a',
    messagingSenderId: '272005928943',
    projectId: 'estudo-6050b',
    authDomain: 'estudo-6050b.firebaseapp.com',
    databaseURL: 'https://estudo-6050b-default-rtdb.firebaseio.com',
    storageBucket: 'estudo-6050b.firebasestorage.app',
    measurementId: 'G-2Y44C9HSV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpFpWDE7AL6SdWiN5OunUItTdoJrQ8Or4',
    appId: '1:272005928943:android:9ee91a01d75f08fdb1c81a',
    messagingSenderId: '272005928943',
    projectId: 'estudo-6050b',
    databaseURL: 'https://estudo-6050b-default-rtdb.firebaseio.com',
    storageBucket: 'estudo-6050b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjGOmQ3FOnL3l_88cRDzv_oS7TFt0_SCo',
    appId: '1:272005928943:ios:8700f0a741caebc1b1c81a',
    messagingSenderId: '272005928943',
    projectId: 'estudo-6050b',
    databaseURL: 'https://estudo-6050b-default-rtdb.firebaseio.com',
    storageBucket: 'estudo-6050b.firebasestorage.app',
    iosBundleId: 'br.com.chatinterno.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJpSeC-vv56xjAbiGVhUOj6JkMieEfb7Y',
    appId: '1:272005928943:web:49f572294dda97c4b1c81a',
    messagingSenderId: '272005928943',
    projectId: 'estudo-6050b',
    authDomain: 'estudo-6050b.firebaseapp.com',
    databaseURL: 'https://estudo-6050b-default-rtdb.firebaseio.com',
    storageBucket: 'estudo-6050b.firebasestorage.app',
    measurementId: 'G-J4YQ7V4FFC',
  );
}
